name    'avi-puppet-test'
version '1.0.1'
source 'https://github.com/avinetworks/avi-puppet'
author 'Avi Networks'
license 'Apache License, Version 2.0'
summary 'Avi networks puppet module'
description 'Avi puppet module allows you to create and manage configurations of objects in Avi Controller.'
project_page 'https://github.com/avinetworks/avi-puppet/'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
